### ISSUE TITLE
Application Full 

### ISSUE THREAD

**Issue by kanishkcs** [HousewareHQ/frontend-engineering-octernship#13]
Hey @shubh24  @theBstar  @ashwinexe  ,

I am Intrested in this octernship , as I am a React Js Developer , i would love to work on this task, but when i went to apply on github it says applicants full, i dont want to miss this Golden opportunity.

is there any scope that i can submit this task ? 
I have gone through the `ReadMe` and i fullfill the requirments also.

Can i showcase my skills by completing this task .

Thank you for your time and consideration. I look forward to hearing from you soon.

**Comment by shubh24** [comment]
Hey @kanishkcs Apologies, but we've hit the applications limit as defined in Github Classroom.
