### ISSUE TITLE
Accidently Merged Pull Request

### ISSUE THREAD

**Issue by rohittp0** [HousewareHQ/frontend-engineering-octernship#14]
Hi, I was trying to move some commits that I accidentally made to the main branch to the Feedback branch and this caused the auto-generated pull request to be closed, what should I do now?

This is my repo: https://github.com/HousewareHQ/houseware---frontend-engineering-octernship-rohittp0
The closed pull request: https://github.com/HousewareHQ/houseware---frontend-engineering-octernship-rohittp0/pull/1

**Comment by manu31shukla** [comment]
You can undo the pull request by reverting from pull request list .

**Comment by rohittp0** [comment]
> You can undo the pull request by reverting from pull request list .

There is no revert option available.

![github com_HousewareHQ_houseware---frontend-engineering-octernship-rohittp0_pull_1](https://user-images.githubusercontent.com/45072928/225711918-f1f322f4-a100-45bf-b824-147a3c3e706b.png)


When I try using CLI, `gh pr reopen 1`, I get

> `X Pull request #1 (Feedback) can't be reopened because it was already merged`

So can I create a new PR and copy over all the details from the old one?

**Comment by rohittp0** [comment]
I have created a new [pull request](https://github.com/HousewareHQ/houseware---frontend-engineering-octernship-rohittp0/pull/2). Hope it's ok.

**Comment by JuanObandoDev** [comment]
[#6](https://github.com/HousewareHQ/frontend-engineering-octernship/issues/6#issuecomment-1467401306) i think this can help u
