### ISSUE TITLE
Private repository

### ISSUE THREAD

**Issue by SamChus** [HousewareHQ/frontend-engineering-octernship#15]
Please should I fork the task repo direct from HousewareHQ or use the private repo?
Because I observed a private repository was created for me, which has the github-classroom[bot] in it.

I am open for feedback and correction.

**Comment by CyberGA** [comment]
> Please should I fork the task repo direct from HousewareHQ or use the private repo? Because I observed a private repository was created for me, which has the github-classroom[bot] in it.
> 
> I am open for feedback and correction.

The private repo
