### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by ARYA-RAY** [HousewareHQ/frontend-engineering-octernship#16]
I have pushed my changes to the main branch, do I have to make a PR now? or will it be automatically checked?

**Comment by YessBlack** [comment]
I also have the same doubt

**Comment by narayan954** [comment]
> I have pushed my changes to the main branch, do I have to make a PR now? or will it be automatically checked?

if you made the commits to the main branch, that's fine according to the updated readme. You should be able to see the committed changes in the auto generated pull request which will be graded actually

**Comment by ARYA-RAY** [comment]
@narayan954 actually i did the entire work in the feedback branch as it was mentioned before , then i merged the changes to the main branch, so the only commit shown in the auto generated pr is the 'merge feedback to main' all the other commits are in the feedback branch, will this be a problem?
