### ISSUE TITLE
Few questions regarding the assignment

### ISSUE THREAD

**Issue by krutagna10** [HousewareHQ/frontend-engineering-octernship#23]
1. Can user enter number or symbols as an input ? (or should I throw an error message saying only alphabets are allowed).
 2. What about uppercase letters, should I convert them to lowercase if user enters them, or should both lowercase and uppercase letters   be treated the same.
 3. What if the user clicks on a character which is only present one time, should I disable the delete button for such character?
 4. Should I directly show success header when user string a string which has no repetition?

**Comment by Superfly101** [comment]
The following closed issues should answer most of your questions:
* https://github.com/HousewareHQ/frontend-engineering-octernship/issues/7
* https://github.com/HousewareHQ/frontend-engineering-octernship/issues/3

**Comment by whalewalker** [comment]
If I understand correctly, you're suggesting that after cloning the forked repository, all changes should be made on the main branch and a pull request (PR) should then be created to merge these changes into the feedback branch, is that correct, 
@Superfly101 @krutagna10 @theBstar

**Comment by Ehceyn** [comment]
> 

I have same question
