### ISSUE TITLE
Github Classroom PR got closed by mistake.

### ISSUE THREAD

**Issue by heysujal** [HousewareHQ/frontend-engineering-octernship#25]
@sp35 @theBstar   I did my work on the `main `branch and then I realized that the work is to be pushed to the `feedback `branch. In order to do so, I merged the `main `branch into my `feedback `branch and then removed changes from the `main `branch using a hard reset. But, I didn't notice that the PR by GitHub classroom got merged automatically. I didn't understand why the PR got merged because I was doing something different which is merging `main `into `feedback `and not merging `feedback `into `main`.
I have made another PR from my feedback branch now. Does that work ?

**Comment by JuanObandoDev** [comment]
i'm in the same situation, i push my work from local repository in main branch to feedback branch in remote repository as the readme file indicated, but the github classroom PR got merged automatically, i wonder if that can be solved or if that affects the selection process?
