### ISSUE TITLE
README FILE & PR DESCRIPTION RELATED ISSUE 

### ISSUE THREAD

**Issue by babboe1** [HousewareHQ/frontend-engineering-octernship#28]
Good day everyone, 
In the private repository generated for us to work in, they are two README files,
- The README in the main directory which contains the instructions and company details
- The README in the app directory where we are working on

In the task description, it is expected to write a README & a PR description for the project, naturally, I wrote my instructions in the second README file located in the app directory.

In the Task submission, it is stated to add instructions/assumptions/any other remarks at the beginning of the README file for the reviewers to take a look.

For the PR description, It was written when I created a PR to merge from the feedback branch to the main branch

My question is;
-  Which README file are we supposed to add instructions/assumptions/any other remarks as stated above
- If I have the instruction to run the app in the second README file located in the app directory, do I have to copy it to the README file in the main directory 
-  How do I ensure that the reviewer will see the PR description from the feedback branch to the main branch since it has already been merged by me
 (P.S The PR merged by me is not the auto-generated PR for feedback/asking questions by the reviewers )

**Comment by JuanObandoDev** [comment]
I think that the readme file that must be modified is the one located in the app folder, where the getting started with react is located, 'cause I see the readme file located in the main directory, is just the description of the task
