### ISSUE TITLE
Changes in different branches are synced

### ISSUE THREAD

**Issue by contigen** [HousewareHQ/frontend-engineering-octernship#29]
Hello HousewareHQ

The task submission section stated in the README file included says to use the feedback branch to complete the task; during work, I realised the changes were synced with the main branch and vice-versa, is this intentional or is something wrong? Could you give detailed instructions on how to submit the assignment ?I've been done for a few days now.
Thanks

**Comment by babboe1** [comment]
Hello @contigen , I believe the detailed instructions on how to submit the assignment have been resolved in #6, you can check it out for more clarification on your issue

**Comment by contigen** [comment]
Thank you a lot!

**Comment by contigen** [comment]
False alarm, I realised what happened. My bad.
