### ISSUE TITLE
Regarding the submission of the project

### ISSUE THREAD

**Issue by KevinA-cpu** [HousewareHQ/frontend-engineering-octernship#34]
Hello Houseware team! after much research looking into issues/pull requests I was led to believe that I to submit the project I need to do 2 things:

1. Push all my code to main
2. Open a pull request on this repo to submit, host the project if possible

I believe that I'm missing something regarding the Github classroom, I went to the Github Classroom page and I can only create a new classroom, how can I see instructions on how to submit?

Thank you for reading and I hope this issue can be resolved soon!

**Comment by narayan954** [comment]
@KevinA-cpu I'm pretty sure, point 2 was mentioned nowhere, instead it was mentioned something like, the auto generated pull request on your repo is the one where you task submission lies and should not be closed at all, evaluations shall be done on that only. 
Ps: You should be able to see changes and commits you made in the auto generated pr by github classroom bot

**Comment by KevinA-cpu** [comment]
thanks for your reply! point 2 was a combination of the pull requests I saw opened and one of the member of Houseware comment that hosting the project make you standout. I suppose I have done all I'm suppose to do.

**Comment by narayan954** [comment]
> thanks for your reply! point 2 was a combination of the pull requests I saw opened and one of the member of Houseware comment that hosting the project make you standout. I suppose I have done all I'm suppose to do.

best of luck mate! 🍀

**Comment by whalewalker** [comment]
@KevinA-cpu @narayan954, quick question, did I follow the correct process to submit my project? Let me know if I missed any steps.

1. I forked repo is created to my repo
2. I clone this repo and cd into the app directory
3. I creates a branch and make all the changes and commit there
4. I push to my branch
5. Create a PR to main branch 

Please what am i missing ?

**Comment by DevYemi** [comment]
@whalewalker You forked the repo ?

i'm not sure but i thought we were supposed to clone the project, and make changes to the auto generated feedback branch.

**Making changes on the auto generated feedback branch to complete the task**

**Comment by whalewalker** [comment]
@DevYemi, when i add the project from octernship website, the project  was forked to my repo automatically. Do you think that's the one I should clone? Can you please guide me if I'm mistaken?

**Comment by DevYemi** [comment]
@whalewalker Yeah you should have cloned the repo that was forked automatically.

You should have cloned it and made all your code changes in the `main branch`, the feedback branch was meant to be used by the reviewer to ask questions and give feedback on the project.

Check out this issue on submission, one of the Houseware member explained the submission requirement in detail there
#6

**Comment by whalewalker** [comment]
If I understand correctly, you're suggesting that after cloning the forked repository, all changes should be made on the main branch and a pull request (PR) should then be created to merge these changes into the feedback branch, is that correct, @DevYemi?

**Comment by KevinA-cpu** [comment]
here's the story from the start, when you sign up for Octernship there's a new repo automatically created for you, what you're supposed to do was clone that repo and work on the Feedback branch, however Houseware change their Instructions now you have to work on the main branch, not the Feedback branch.

**Comment by whalewalker** [comment]
> here's the story from the start, when you sign up for Octernship there's a new repo automatically created for you, what you're supposed to do was clone that repo and work on the Feedback branch, however Houseware change their Instructions now you have to work on the main branch, not the Feedback branch.

If i work from the feedback branch, which branch will i create a PR against ? is it the feedback branch?

**Comment by whalewalker** [comment]
Thanks, @DevYemi. Currently, my latest changes are on the main branch and I haven't made any modifications to the feedback branch. Is that alright?

**Comment by DevYemi** [comment]
Yeah that's perfectly fine, that was actually the workflow explained in that list in my previous reply.

@whalewalker  once you have updated your readme file with how to run the project locally and give details about any other information about the project then you are fine, the project will automatically be submitted on the deadline date

**Comment by whalewalker** [comment]
> Yeah that's perfectly fine, that was actually the workflow explained in that list in my previous reply.
> 
> @whalewalker once you have updated your readme file with how to run the project locally and give details about any other information about the project then you are fine, the project will automatically be submitted on the deadline date

However, it is not appearing in the list of pull requests from the Houseware repository

**Comment by whalewalker** [comment]
Or am i missing something

**Comment by DevYemi** [comment]
No you ain't, it actually ain't suppose to show there.

Look at #10 pull request, a houseware member corrected the person that made the pull request there.
