### ISSUE TITLE
octernship details

### ISSUE THREAD

**Issue by debanjo31** [HousewareHQ/frontend-engineering-octernship#4]
do I install a new react app to work on this project?
how do I submit it after working on this project?

Thanks

**Comment by samuel-ma** [comment]
@debanjo31 
Just create a fork and load it on your local device
Run it on your code editor as usual and work on the task
Once your done, just return to this repo and create a pull request and wait for a review
The readme is pretty detailed, walks you thru everything

Let me know what your stuck on exactly

**Comment by manaver** [comment]
@samuel-ma  i completed my project and pushed it in feedback branch and it automatically merged. Now do i need to wait for feedback? Also there is no discussion tab for doubts? And one more question do i need to write about project or only installation procedure in readme?
Thanks!

**Comment by samuel-ma** [comment]
@manaver, wait for a review of your project
You'll receive an email once it's been reviewed so check your emails.

**Comment by manaver** [comment]
Thanks @samuel-ma

**Comment by rahulaarora** [comment]
Hi @samuel-ma, I have completed the assignment and committed to the Main branch, do I have to merge it with the feedback branch?
Thanks!

**Comment by SamChus** [comment]
@manaver, that means we are to pitch our code to the feedback branch?

**Comment by manaver** [comment]
@SamChus i am not really sure is this correct. I follow readme file and push my changes to feedback branch.

**Comment by CyberGA** [comment]
> @SamChus i am not really sure is this correct. I follow readme file and push my changes to feedback branch.

This is right

**Comment by shubh24** [comment]
Please refer to #6 for details regarding submissions
