### ISSUE TITLE
Couldn't create PR

### ISSUE THREAD

**Issue by Damola18** [HousewareHQ/frontend-engineering-octernship#45]
I have finished this task since yesterday but till now, I can't make PR. Anybody getting this issue
<img width="947" alt="image" src="https://user-images.githubusercontent.com/50779080/227945143-23762927-b745-4334-b689-4ace1bcb3af1.png">
This is the error I was getting

**Comment by CodeEvolver** [comment]
Edit the create react app Readme in your app directory.
