### ISSUE TITLE
task successfully done within deadline, what's the next step?

### ISSUE THREAD

**Issue by sohamdata** [HousewareHQ/frontend-engineering-octernship#47]
i've made the final changes at my repo for the [task](https://github.com/HousewareHQ/houseware---frontend-engineering-octernship-sohamdata).

**Comment by theBstar** [comment]
Hey, Thanks for the submission. We have started reviewing submissions. As we are reviewing a large number of submissions expect to hear from us in a few days (might take a couple of weeks in the worst case).
