### ISSUE TITLE
SYNC with feedback branch merged the auto PR 

### ISSUE THREAD

**Issue by babboe1** [HousewareHQ/frontend-engineering-octernship#48]
Before we were told to push all our code to the main branch, I was working on the feedback branch, so I merged the feedback branch to the main branch and continued working on the main branch,

Just a few hours ago, I came to check my repo for any changes or feedback, then I realized that my main branch want in sync with the feedback branch as I had continued to push code to the main branch before the deadline, 

For uniformity, I then decided to sync the main branch with the feedback branch, so from my vscode I decided to merge the main branch into the feedback branch using the  git command "git merge main", then pushed the changes to my feedback branch, 

Coming to Github I realized that the auto feedback PR had also been merged and added as a part of my commit, 
I tried rebasing/reverting the feedback branch to a state before the last commit which was around 2 weeks ago,  hoping the PR will be reopened, but that didn't solve the issue for me, as the PR was never reopened,

I seriously hope this won't hurt my candidacy as I have put in a lot of effort in following every instruction given and fulfilling every task, which resulted in creating a great application 

Please note that this error happened today, I believed the assignment had been submitted automatically on the deadline day just as stated in #6 by @shubh24 , I just want to know if closing the PR wont cost me a chance at reviewing my work

@shubh24 Thank you for your time  ,i await your response

**Comment by shubh24** [comment]
Thanks for writing in, we'll review the assignment as all others.

Sent via Superhuman ( ***@***.*** )
