### ISSUE TITLE
Task Completed But No Response from the Team

### ISSUE THREAD

**Issue by adityassharma-ss** [HousewareHQ/frontend-engineering-octernship#49]
I completed the assignment around 10-12 days ago but yet to hear any update from your side.

**Comment by theBstar** [comment]
Hey, Thanks for the submission. We have started reviewing submissions. As we are reviewing a large number of submissions expect to hear from us in a few days (might take a couple of weeks in the worst case).

**Comment by adityassharma-ss** [comment]
Thank you for letting me know that you have received my submission. Looking forward to hearing from you soon.

**Comment by CyberGA** [comment]
Acknowledged.
