### ISSUE TITLE
Octernship Submission

### ISSUE THREAD

**Issue by Devanshu-17** [HousewareHQ/frontend-engineering-octernship#5]
Hello, I have completed the task successfully and submitted it for review. Can anyone please check if I have submitted it properly, because I was confused by the instructions in the readme file.

**Comment by manaver** [comment]
Hi @Devanshu-17 , i am also participating in this program.  I have a question to ask, Do we need to push the project in feedback branch?

**Comment by Devanshu-17** [comment]
Hey @manaver I pushed it via VS Code. So, I am also not sure about it

**Comment by manaver** [comment]
ok

**Comment by shubh24** [comment]
Please check #6 for any queries about the submissioons
