### ISSUE TITLE
Query about result and updates

### ISSUE THREAD

**Issue by manaver** [HousewareHQ/frontend-engineering-octernship#51]
Hi, @shubh24 , @theBstar I would like to know when the results of the internship will be released, and when we can expect to receive any further updates or information. If there are any specific deadlines or timeframes that we should be aware of, please do let us know.

I would greatly appreciate any information that you can provide, and I thank you in advance for your time and attention to this matter.

**Comment by theBstar** [comment]
All submissions has been reviewed & communication has been done on the PR/New issue on the repo. Thanks for all submissions.
