### ISSUE TITLE
Gotten No Response On Private Repo Submission

### ISSUE THREAD

**Issue by DevYemi** [HousewareHQ/frontend-engineering-octernship#52]
Hi, there.

Firstly i would like to acknowledge that i have gone through the issues and i have seen in issue #51 where @theBstar claimed all submission have been reviewed and feedback has been given, also i saw that it is true as he gave a response to all the devs who submitted through a pull request.

But i worked on the project through a private repo [Link](https://github.com/HousewareHQ/houseware---frontend-engineering-octernship-DevYemi/tree/main) created for me by GitHubClassRoom Bot and after following the procedure on how to submit, i got no response till date, its almost like my work wasn't reviewed. Its fine if its already too late, i just wanted to bring this to you guys notice.

**Comment by theBstar** [comment]
Hey, it's unfortunate that your work didn't get reviewed. We did our best to review all submissions. Your repo wasn't submitted for evaluation. You can host the project somewhere, write a detailed mail and send it to `hiring@houseware.io` and we will have a proper look at it. 

Thank you.
