### ISSUE TITLE
 Which branch should the changes be done?

### ISSUE THREAD

**Issue by naveen521kk** [HousewareHQ/frontend-engineering-octernship#6]
Hello 👋, I'm slightly confused about which branch I should be working on. 
> Students are expected to use the [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow) when working on their project.
>  1. Making changes on the auto generated feedback branch to complete the task.
>  2. Using the auto generated Feedback Pull Request for review and submission
>  3. Using GitHub Discussions to ask any relevant questions regarding the project

These instructions (from the README) in my understanding tell that I should be working on the `feedback` branch. The confusion I got when looking at the auto-generated "Feedback Pull Request" is that the bot created it to merge into `feedback` the changes from `main`, `main -> feedback`, this is as if I should be working on the `main` branch and it'll be merged into the `feedback` branch on review. This is the other way around, actually.

![firefox_KaqDnPZuIE](https://user-images.githubusercontent.com/49693820/224028504-4c7fb3c9-77a4-4770-90e8-c338db69a507.png)

I started committing to the `feedback` branch following the instruction but looks like PR didn't update from that.
I'm confused about this and would like some assistance on what I should do here. Thanks!

cc @ashwinexe since you made the changes in Readme

**Comment by rahulaarora** [comment]
Hi @naveen521kk, I also have the same confusion, I started committing on the Main branch.

**Comment by SamChus** [comment]
Please I really need assistance on this too.

**Comment by shubh24** [comment]
Sure, let us get back here!

**Comment by krcpr007** [comment]
Hii @shubh24 I have the same confusion and also want to know where we do write a readme & a PR description on how to run the project locally.

**Comment by CyberGA** [comment]
Hi, after registration, a repository is automatically generated for you. Check your list of repo, you should see it, then I think the changes should be pushed to the `feedback` repo.

**Comment by krcpr007** [comment]
@CyberGA  so what do we have to do? 
Just push to the generated repo or which branch we have to push main or feedback?

**Comment by CyberGA** [comment]
@krcpr007 according to the instruction, what I did is, I cloned the repo generated for me, then I created another branch and built the solution in there and then `push` that branch to github. Then I made a pull request from that branch into the auto generated `feedback` branch

**Comment by CyberGA** [comment]
> @CyberGA so what do we have to do? Just push to the generated repo or which branch we have to push main or feedback?

@krcpr007  according to the instruction, what I did is, I cloned the repo generated for me, then I created another branch and built the solution in there and then `push` that branch to github. Then I made a pull request from that branch into the auto generated `feedback` branch

**Comment by krcpr007** [comment]
@CyberGA I have pushed my code to the generated repo main branch and I can see the changes as below is it perfect?
![image](https://user-images.githubusercontent.com/80947662/224738959-917e9302-d572-45a2-9d51-4934fe7178df.png)

**Comment by CyberGA** [comment]
> @CyberGA I have pushed my code to the generated repo main branch and I can see the changes as below is it perfect? ![image](https://user-images.githubusercontent.com/80947662/224738959-917e9302-d572-45a2-9d51-4934fe7178df.png)

Yes. Then you can update the README file that is in the app directory with what is required

**Comment by CyberGA** [comment]
> > > @CyberGA I have pushed my code to the generated repo main branch and I can see the changes as below is it perfect? ![image](https://user-images.githubusercontent.com/80947662/224738959-917e9302-d572-45a2-9d51-4934fe7178df.png)
> > 
> > 
> > Yes. Then you can update the README file that is in the app directory with what is required
> 
> Do you mean a PR description on how to run the project locally? Anything else can you add I should write in Readme.md

Yes since a README and a PR description was stated

**Comment by naveen521kk** [comment]
So, where exactly I should push my changes, `main` or `feedback` or to another branch? I've already pushed some commits to `feedback` branch, should I rewrite the history there (that is make it so that it's how it was originally?)?

**Comment by CyberGA** [comment]
> So, where exactly I should push my changes, `main` or `feedback` or to another branch? I've already pushed some commits to `feedback` branch, should I rewrite the history there (that is make it so that it's how it was originally?)?

You can write your solution on the `feedback` branch and push or make a pull request to the `feedback` bracnh

**Comment by Kdsingh333** [comment]
I have a one doubt regarding  houseware---backend project , is there any restriction using Golang Framework , Orm and database or we can use any framework in this project  @shubh24 ??

**Comment by shubh24** [comment]
> I have a one doubt regarding houseware---backend project , is there any restriction using Golang Framework , Orm and database or we can use any framework in this project @shubh24 ??

Please raise this issue in the relevant repository.

**Comment by shubh24** [comment]
Hey all, thanks for your patience here! 

As has been mentioned above in the thread, we'd suggest the following for submission:
- Please push your final code changes to your `main` branch
- Please add your instructions/assumptions/any other remarks in the beginning of the Readme file and the reviewers will take a look
- The PR created called `Feedback` will be used for sharing any feedback/asking questions by the reviewers, please make sure you do not close the Feedback PR.
- The assignment will be automatically submitted on the "Assignment Deadline" date -- you don't need to do anything apart from what is mentioned above.
 
Updating the above instructions in the Readme as well. Feel free to ask any further questions on this Issue.

**Comment by manaver** [comment]
@shubh24 i pushed my code into feedback branch (not on main) and pr automatically merged? Is there anything that i need to correct?

**Comment by shubh24** [comment]
> @shubh24 i pushed my code into feedback branch (not on main) and pr automatically merged? Is there anything that i need to correct?

No need to worry -- the reviewers will check on your repository.

**Comment by manaver** [comment]
Thanks sir

**Comment by Ravikisha** [comment]
how to submit my code to the reviewer?

**Comment by ARYA-RAY** [comment]
@shubh24 I have pushed my changes to the main branch, do I need to create a PR now or will it be checked automatically?

**Comment by naveen521kk** [comment]
Thank you for the detailed answer @shubh24! I'll close the issue then.

**Comment by AbhishekBhamare** [comment]
@shubh24 Should we merge the PR or Reviewer will do it?
