### ISSUE TITLE
Constraints on the project

### ISSUE THREAD

**Issue by adarsh500** [HousewareHQ/frontend-engineering-octernship#7]
Hey Mentors, I had a few questions

1. Would we need a maximum limit of characters for the string?
2. Do we have to consider numbers and special characters as valid input
3. Are we allowed to use tab-based navigation, or is it limited to route-based navigation only?

**Comment by Abusayid693** [comment]
4. Should we consider empty space in between string as valid input eg `aba aba f`

**Comment by manaver** [comment]
@Abusayid693 no, check the screen1 description. If the input field is empty or has only space characters, the user should be shown an alert asking them to provide a non-empty value.

**Comment by adarsh500** [comment]
Yes, but here the case is both empty space and valid letters combined

**Comment by theBstar** [comment]
For simplicity let's not do any special treatment for special characters. Treat them as valid input. 

Not navigation, lets implement route-based navigation.

**Comment by theBstar** [comment]
@adarsh500 Let me know if this answers your q. Feel free to close the issue if it does.

**Comment by adarsh500** [comment]
That helps, thanks !

**Comment by vaibhav-xt** [comment]
> @adarsh500 Let me know if this answers your q. Feel free to close the issue if it does.



> For simplicity let's not do any special treatment for special characters. Treat them as valid input.
> 
> Not navigation, lets implement route-based navigation.

In the task written provide a non-empty value. Therefore I implemented and will navigate to screen 2. Is this will correct?
