### ISSUE TITLE
Regarding Task Submissions

### ISSUE THREAD

**Issue by adityassharma-ss** [HousewareHQ/frontend-engineering-octernship#8]
Can we have a more detailed instructions for the submission of the task?
It's quite confusing right now that how the review for the code will be done.

**Comment by shubh24** [comment]
Please refer to #6 for details

**Comment by adityassharma-ss** [comment]
Thank You for your feedback. I have pushed & updated the code in main branch. But the repo is private by default. It won't be an issue. RIght?
