### ISSUE TITLE
Want to apply in Octernship

### ISSUE THREAD

**Issue by surathjhakal** [HousewareHQ/frontend-engineering-octernship#9]
Hello everyone,

I want to apply to this project in GitHub Octernship but it says you need to contribute to open source, yeah so till now I haven't contributed to any project but I'm interested in contributing to this project
I have worked in a Canadian startup named sci-spot for 9 months, I have worked on reactjs, typescript,aws, and MongoDB.
I want to start my journey by contributing to open source, is it possible for me to apply it in some other way?

**Comment by rishav-22** [comment]
Find a open source project, Contribute it by resolving issue and become eligible for internship

**Comment by surathjhakal** [comment]
Will I be eligible if I merge one pr to an open-source project?
Because the deadline for applying for this internship will end soon
